import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "리액트 학습 섹션1",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="antialiased">{children}</body>
    </html>
  );
}
